-- markov.lua
-- Random word generation via basic markov-chain

local markov = {}

--- Process a corpus from a table
-- Expects as input a table of strings making up the text corpus.
-- `order` specifies the Markov-Chain order.
function markov.init(corpus, order)
    local map = {}
    map.initiators  = {} -- All initiating strings of length `order`
    map.terminators = {} -- All terminating strings of length `order`
    map.options = {}     -- Options form every order-length ngram
    map.order = order

    for _, word in ipairs(corpus) do
        if #word > order then
            for i=order, #word-1, 1 do
                local sprev =  word:sub(1+i-order,i):lower()
                local snext = word:sub(i+1,i+1):lower()
                if i == #word - 1 then
                    local term = (sprev..snext):sub(2)
                    map.terminators[term] = true
                end
                if map.options[sprev] == nil then
                    map.options[sprev] = {snext}
                    if i == order then
                        table.insert(map.initiators, sprev)
                    end
                else
                    table.insert(map.options[sprev], snext)
                end
            end
        end
    end
    return map
end

--- Generate a word according to an existing map, up to `length`
-- @param map a corpus generated by markov.init
-- @param length the maximum length of the desired word
-- @rng (optional) a random number generator table that can be called as math.random
function markov.word(map, length, rng)
    if rng == nil then rng = math.random end
    local order = map.order
    local word = map.initiators[rng(#map.initiators)]
    while true  do
        local sprev = word:sub(#word-order+1)
        local poss_letter = map.options[sprev]
        if poss_letter == nil then break end
        local next_letter = poss_letter[rng(#poss_letter)]
        word = word .. next_letter
        if #word == length then break end
    end
    -- Trim to permissable terminating chunk
    while map.terminators[word:sub(-order)] == nil do
        word = word:sub(1,#word-1)
        if #word < length / 2 then break end
    end
    return word
end

return markov

