name: CI
on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master, dev ]
jobs:
  build-distributables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nhartland/love-build@v1-beta5
      id: love-build
      with:
        app_name: 'golflike'
        love_version: '11.5'
        dependencies: 'rockspec/golflike-scm-1.rockspec'
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ steps.love-build.outputs.macos-filename }}
          ${{ steps.love-build.outputs.win32-filename }}
          ${{ steps.love-build.outputs.love-filename }}
