name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-distributables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nhartland/love-build@master
      id: love-build
      with:
        app_name: 'golflike'
        love_version: '11.3'
        enable_loverocks: true 
    - uses: actions/upload-artifact@v1
      with:
        name: golflike-macos_build
        path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: golflike-win32_build
        path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v1
      with:
        name: golflike-love_build
        path: ${{ steps.love-build.outputs.love-filename }}
